//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests Team.
        /// </summary>
        public static string btnInfoGuestsTeam {
            get {
                return ResourceManager.GetString("btnInfoGuestsTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Team.
        /// </summary>
        public static string btnInfoHomeTeam {
            get {
                return ResourceManager.GetString("btnInfoHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests Team.
        /// </summary>
        public static string cbAwayTeam {
            get {
                return ResourceManager.GetString("cbAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Team.
        /// </summary>
        public static string cbHomeTeam {
            get {
                return ResourceManager.GetString("cbHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPITAN:.
        /// </summary>
        public static string lblCaptainText {
            get {
                return ResourceManager.GetString("lblCaptainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lblContestText {
            get {
                return ResourceManager.GetString("lblContestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAWS:.
        /// </summary>
        public static string lblDrawsText {
            get {
                return ResourceManager.GetString("lblDrawsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMES PLAYED:.
        /// </summary>
        public static string lblGamesPlayedText {
            get {
                return ResourceManager.GetString("lblGamesPlayedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOALS AGAINST:.
        /// </summary>
        public static string lblGoalsAgainstText {
            get {
                return ResourceManager.GetString("lblGoalsAgainstText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOALS DIFFERENCES:.
        /// </summary>
        public static string lblGoalsDifferencesText {
            get {
                return ResourceManager.GetString("lblGoalsDifferencesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOALS FOR:.
        /// </summary>
        public static string lblGoalsForText {
            get {
                return ResourceManager.GetString("lblGoalsForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOALS:.
        /// </summary>
        public static string lblGoalsText {
            get {
                return ResourceManager.GetString("lblGoalsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLangText {
            get {
                return ResourceManager.GetString("lblLangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOSSES:.
        /// </summary>
        public static string lblLossesText {
            get {
                return ResourceManager.GetString("lblLossesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string lblPlayerName {
            get {
                return ResourceManager.GetString("lblPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POINTS:.
        /// </summary>
        public static string lblPointsText {
            get {
                return ResourceManager.GetString("lblPointsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string lblResolutionText {
            get {
                return ResourceManager.GetString("lblResolutionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINS:.
        /// </summary>
        public static string lblWinsText {
            get {
                return ResourceManager.GetString("lblWinsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YELLOWCARDS:.
        /// </summary>
        public static string lblYellowCardsText {
            get {
                return ResourceManager.GetString("lblYellowCardsText", resourceCulture);
            }
        }
    }
}
